/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mypackage;

import java.awt.event.KeyEvent;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import java.util.UUID;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperExportManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JRDesignQuery;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author HP
 */
public class BuiltyFrame extends javax.swing.JFrame {
    
    Connection con;
    Statement stmt;
    public ResultSet rs;
    
    int sno_flag = 0;

    /**
     * Creates new form BuiltyFrame
     */
    public BuiltyFrame() {
        initComponents();
        try{
            
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/Bilty","root","root");
            stmt = con.createStatement();
           
            
            //Fetching Current Date
            DateFormat df = new SimpleDateFormat("dd/MM/yyyy   HH:mm:ss");
            Date date = new Date();
            txtDate.setText(df.format(date));
            
            txtBilty.setText("5.0");
            
            txtConsignee.setEnabled(false);
            txtConsignee_GST.setEnabled(false);
            txtConsignor.setEnabled(false);
            txtConsignor_GST.setEnabled(false);
            
            txtPackages.setEnabled(false);
            txtDescription.setEnabled(false);
            txtWeight.setEnabled(false);
            
            txtTo.setEnabled(false);
            txtFrieght.setEnabled(false);
            txtHammali.setEnabled(false);
            
            
           }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel13 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtConsignor = new javax.swing.JTextField();
        txtConsignor_GST = new javax.swing.JTextField();
        txtConsignee = new javax.swing.JTextField();
        txtConsignee_GST = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        rdbToPay = new javax.swing.JRadioButton();
        rdbPaid = new javax.swing.JRadioButton();
        rdbBilled = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtSno = new javax.swing.JTextField();
        txtDate = new javax.swing.JTextField();
        txtFrom = new javax.swing.JTextField();
        txtTo = new javax.swing.JTextField();
        txtFrieght = new javax.swing.JTextField();
        txtHammali = new javax.swing.JTextField();
        txtBilty = new javax.swing.JTextField();
        txtGrand = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        btnClear = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblData = new javax.swing.JTable();
        btnCalculate = new javax.swing.JButton();
        btnCreate = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtPackages = new javax.swing.JTextField();
        txtDescription = new javax.swing.JTextField();
        txtWeight = new javax.swing.JTextField();
        btnDelete = new javax.swing.JButton();
        lblValidate = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel13.setText("BILTY BOOK");

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Consignor:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Consignor GSTNo. :");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Consignee GSTNo. :");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Consignee: ");

        txtConsignor.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        txtConsignor_GST.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        txtConsignee.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtConsignee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtConsigneeActionPerformed(evt);
            }
        });

        txtConsignee_GST.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtConsignor)
                    .addComponent(txtConsignor_GST)
                    .addComponent(txtConsignee)
                    .addComponent(txtConsignee_GST, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtConsignor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtConsignor_GST, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtConsignee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtConsignee_GST, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("S.NO: ");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("Date: ");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("From:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("To: ");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("Payment Status");

        buttonGroup1.add(rdbToPay);
        rdbToPay.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rdbToPay.setText("To Pay");

        buttonGroup1.add(rdbPaid);
        rdbPaid.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rdbPaid.setText("Paid");

        buttonGroup1.add(rdbBilled);
        rdbBilled.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rdbBilled.setText("To Be Billed");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Frieght: ");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Hammali: ");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Bilty Charge: ");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Grand Total: ");

        txtSno.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtSno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSnoKeyTyped(evt);
            }
        });

        txtDate.setEditable(false);
        txtDate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        txtFrom.setEditable(false);
        txtFrom.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtFrom.setText("INDORE");

        txtTo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        txtFrieght.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtFrieght.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFrieghtKeyTyped(evt);
            }
        });

        txtHammali.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtHammali.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtHammaliKeyTyped(evt);
            }
        });

        txtBilty.setEditable(false);
        txtBilty.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtBilty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBiltyActionPerformed(evt);
            }
        });
        txtBilty.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBiltyKeyTyped(evt);
            }
        });

        txtGrand.setEditable(false);
        txtGrand.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtGrand.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtGrandKeyTyped(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 0, 51));
        jLabel18.setText("VALIDATE");
        jLabel18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel18MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(rdbToPay))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel12)
                            .addComponent(jLabel11))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtSno)
                            .addComponent(txtDate)
                            .addComponent(txtFrom, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                            .addComponent(txtTo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel18)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel7)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtFrieght)
                            .addComponent(txtHammali)
                            .addComponent(txtBilty)
                            .addComponent(txtGrand, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(rdbPaid)
                                .addGap(36, 36, 36)
                                .addComponent(rdbBilled))
                            .addComponent(jLabel14))))
                .addGap(0, 83, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(txtSno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5))
                    .addComponent(txtFrom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtTo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(jLabel14)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rdbToPay)
                            .addComponent(rdbPaid)
                            .addComponent(rdbBilled))
                        .addGap(41, 41, 41)
                        .addComponent(jLabel7))
                    .addComponent(txtFrieght, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtHammali, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtBilty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtGrand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        btnClear.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnClear.setText("CLEAR");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        btnExit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnExit.setText("EXIT");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        tblData.setAutoCreateRowSorter(true);
        tblData.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tblData.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tblData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Packages", "Description", "Weight Actual"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblData);
        if (tblData.getColumnModel().getColumnCount() > 0) {
            tblData.getColumnModel().getColumn(0).setPreferredWidth(5);
        }

        btnCalculate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCalculate.setText("CALCULATE");
        btnCalculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalculateActionPerformed(evt);
            }
        });

        btnCreate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCreate.setText("CREATE");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setText("Description:");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setText("Packages:");

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setText("Weight Actual:");

        txtPackages.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtPackages.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPackagesKeyTyped(evt);
            }
        });

        txtDescription.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        txtWeight.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtWeight.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtWeightKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel16)
                    .addComponent(jLabel15)
                    .addComponent(jLabel17))
                .addGap(33, 33, 33)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtPackages)
                    .addComponent(txtDescription)
                    .addComponent(txtWeight, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(txtPackages, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txtDescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(txtWeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
        );

        btnDelete.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnDelete.setText("DELETE");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        lblValidate.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblValidate.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addGap(414, 414, 414))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 611, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(176, Short.MAX_VALUE)
                        .addComponent(btnCreate)
                        .addGap(147, 147, 147)
                        .addComponent(btnDelete)
                        .addGap(206, 206, 206)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCalculate)
                        .addGap(47, 47, 47)
                        .addComponent(btnClear)
                        .addGap(53, 53, 53)
                        .addComponent(btnExit))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblValidate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(19, 19, 19))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel13)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnDelete)
                            .addComponent(btnCreate))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 24, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCalculate)
                            .addComponent(btnClear)
                            .addComponent(btnExit))
                        .addGap(47, 47, 47)
                        .addComponent(lblValidate, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtConsigneeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtConsigneeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtConsigneeActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed

        try 
        {
            int i = JOptionPane.showConfirmDialog(null,"Are you sure, you want to clear this bill?");
            if(i==0)
            {
                    String sno = txtSno.getText().toString();
                    //txtBilty.setText("");
                    txtConsignor_GST.setText("");
                    txtConsignee.setText("");
                    txtConsignee_GST.setText("");
                    txtConsignor.setText("");
                    txtFrieght.setText("");
                    txtGrand.setText("");
                    txtHammali.setText("");
                    txtSno.setText("");
                    txtTo.setText("");
                    txtWeight.setText("");
                    txtPackages.setText("");
                    txtDescription.setText("");
                    
                    
                    rdbBilled.setSelected(false);
                    rdbPaid.setSelected(false);
                    rdbToPay.setSelected(false);
                    
                    txtSno.setEnabled(true);
                    txtSno.setEditable(true);
                    
                    DefaultTableModel tbl = (DefaultTableModel) tblData.getModel();
                    tbl.setRowCount(0);
                   
                    if(!(sno.equals("")))
                    {
                        String delBill = "DELETE FROM Bilty_Desc WHERE SNO = '"+sno+"'";
                        stmt.executeUpdate(delBill);

                        String del = "DELETE FROM Bilty_Master WHERE SNO = '"+sno+"'";
                        stmt.executeUpdate(del);
                    }
                    JOptionPane.showMessageDialog(null, "Bill deleted!");
            }
        }
        
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }

    }//GEN-LAST:event_btnClearActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnCalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalculateActionPerformed

        try
        {
            String from = "Indore";
            String payment_status = "";
            
            double  bilty_charge = 5.0;
            
            // Saving Values into variable  
            String consignee = txtConsignee.getText().trim();
            String consignor = txtConsignor.getText().trim();
            String consignee_gst = txtConsignee_GST.getText().trim();
            String consignor_gst = txtConsignor_GST.getText().trim();
            
            String sno = txtSno.getText().trim();
            String bill_date = txtDate.getText().trim();
            String to = txtTo.getText().trim();
            
            if(rdbToPay.isSelected())
            {
                payment_status = "To Pay";
            }
            else if(rdbPaid.isSelected())
            {
                payment_status = "Paid";
            }
            else if(rdbBilled.isSelected())
            {
                payment_status = "Billed";
            }
            
            String frieght_str = txtFrieght.getText();
            String hammali_str = txtHammali.getText();
            
            double friegth = 0;
            double hammali = 0;
            
            if(frieght_str != null && frieght_str.length() > 0)
            {
               friegth = (Double.parseDouble(txtFrieght.getText()));
            }
            
            if(hammali_str != null && hammali_str.length() > 0)
            {
                hammali = (Double.parseDouble(txtHammali.getText()));
            }
                  
            double grand_total = friegth + hammali + bilty_charge;
            
            if(!(consignor.equals("") || consignee.equals("") || sno.equals("") || to.equals("") || payment_status.equals("")))
            {
                lblValidate.setText("");
                    if(sno_flag == 1)
                    {
                        String upd_qry = "UPDATE Bilty_Master SET Consignor = '"+consignor+"', CR_GSTNO = '"+consignor_gst+"' , Consignee =  '"+consignee+"' , CN_GSTNO = '"+consignee_gst+"', Date_Bill = '"+bill_date+"', From_City= '"+from+"', To_City= '"+to+"', Payment_Status= '"+payment_status+"',freight= "+friegth+", hammali= "+hammali+",bilty_charge= "+bilty_charge+", grand_total= "+grand_total+"  WHERE SNO = '"+sno+"' "; 
                        stmt.executeUpdate(upd_qry);

                        txtGrand.setText(grand_total + "");
                        //JOptionPane.showMessageDialog(null, "Data is successfully saved! Please proceed for printing");
                        
                       
                        // Generating JASPER REPORTS 
                        String reportUrl = "/mypackage/BiltyReceipt.jrxml"; //path of your report source.
                        InputStream reportFile = null;
                        reportFile = getClass().getResourceAsStream(reportUrl);
                        //reportFile = new FileInputStream(reportUrl);
                        JasperDesign jasdi=JRXmlLoader.load(reportFile);
                        //String billquery = "SELECT USER.BILLNO, USER.NAME, USER.CONTACT_NO, USER.ADDRESS, USER.GSTIN, USER.BILL_DATE, USER.TOTAL_AMOUNT, BILL.HSN_CODE, BILL.ITEM_NAME, BILL.QUANTITY, BILL.TAX_SLAB, BILL.SELLING_PRICE, BILL.BASIC_PRICE, BILL.CGST, BILL.SGST, BILL.TOTAL_PRICE FROM BILL, USER WHERE USER.BILLNO = BILL.BILLNO AND SNO = '"+sno+"'";
                        String billquery = "SELECT Bilty_Master.SNO, Bilty_Master.Consignor, Bilty_Master.CR_GSTNO, Bilty_Master.Consignee, Bilty_Master.CN_GSTNO, Bilty_Master.Date_Bill, Bilty_Master.From_City, Bilty_Master.To_City, Bilty_Master.Payment_Status, Bilty_Master.freight, Bilty_Master.hammali, Bilty_Master.bilty_charge, Bilty_Master.grand_total, Bilty_Desc.Packages, Bilty_Desc.Description, Bilty_Desc.Weight FROM Bilty_Master, Bilty_Desc WHERE Bilty_Master.SNO = Bilty_Desc.SNO AND Bilty_Master.SNO = '"+sno+"'";

                        JRDesignQuery newQuery = new JRDesignQuery();
                        newQuery.setText(billquery);
                        jasdi.setQuery(newQuery);

                        HashMap<String, Object> para = new HashMap<>();
                        para.put("Bilty_Master.SNO",sno);

                        JasperReport js=JasperCompileManager.compileReport(jasdi);
                        //JasperReport js = (JasperReport) JRLoader.loadObject(reportUrl);
                        JasperPrint jp=JasperFillManager.fillReport(js,para,con);
                        JasperExportManager.exportReportToPdfFile(jp,"E:\\BiltyBook\\"+sno+".pdf");
                        JOptionPane.showMessageDialog(null, "YOUR BILTY IS GENERATED SUCCESSFULLY");
                        dispose();
        //                WelcomeFrame open = new WelcomeFrame();
        //                open.setVisible(true);

                        JasperViewer.viewReport(jp, false);
                    }
                    else
                    {
                        JOptionPane.showMessageDialog(null, "Please select the correct SNO");
                        txtSno.requestFocusInWindow();
                    }
            
            }
            else
            {
                    lblValidate.setText("Please enter the required details!!!");
            }   
        }
        
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }


    }//GEN-LAST:event_btnCalculateActionPerformed

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed

        try
        {
            if(sno_flag == 1)
            {
                String sno = txtSno.getText().trim();
           
          
                String packg = txtPackages.getText().trim();
                String descip = txtDescription.getText().trim();
                String weight = txtWeight.getText().trim();

                if(!(sno.equals("") || packg.equals("") || descip.equals("") || weight.equals("")))
                {
                lblValidate.setText("");
                String ins_qry = "INSERT INTO BILTY_DESC VALUES ('"+sno+"', '"+packg+"','"+descip+"', '"+weight+"')";
                stmt.executeUpdate(ins_qry);

                DefaultTableModel tbl = (DefaultTableModel) tblData.getModel();
                 tbl.insertRow(tbl.getRowCount(), new Object[]
                 {packg, descip, weight});
            
                txtPackages.setText("");
                txtDescription.setText("");
                txtWeight.setText("");
                }
                else
                {
                    lblValidate.setText("Enter the Table Details!!!");
                }
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Please select the correct SNO");
                txtSno.requestFocusInWindow();
            }
        }
        
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btnCreateActionPerformed

    private void txtBiltyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBiltyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBiltyActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed

         try 
        {
            String sno = txtSno.getText().trim();
            DefaultTableModel model = (DefaultTableModel) tblData.getModel();
            int select = tblData.getSelectedRow();
            
            if(select != -1)
            {
            String descrip =  (tblData.getModel().getValueAt(select,1).toString());
            String qry = "DELETE FROM Bilty_Desc WHERE SNO ='"+sno+"' AND Description='"+descrip+"'";
            stmt.executeUpdate(qry);

            model.removeRow(select);
           
            }
            else
            {
                JOptionPane.showMessageDialog(null,"Please select an item to remove.");
            }
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void jLabel18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel18MouseClicked
        // TODO add your handling code here
       try
       {
            String sno = txtSno.getText().trim();
           
            // Checking the SNO
            if(!(sno.equals("")))
            {
                    String qry = "SELECT SNO FROM Bilty_Master WHERE SNO =  '"+sno+"'";
                    rs = stmt.executeQuery(qry);

                    lblValidate.setText("");
                    if(rs.next() == false)
                    {
                        System.out.println("SNO is available");
                        txtSno.setEditable(false);
                        txtSno.setEnabled(false);
                        String ins_qry = "INSERT INTO Bilty_Master (SNO) VALUES ('"+sno+"')";
                        stmt.executeUpdate(ins_qry);

                        txtConsignee.setEnabled(true);
                        
                        txtConsignee_GST.setEnabled(true);
                        txtConsignor.setEnabled(true);
                        txtConsignor_GST.setEnabled(true);

                        txtPackages.setEnabled(true);
                        txtDescription.setEnabled(true);
                        txtWeight.setEnabled(true);

                        txtTo.setEnabled(true);
                        txtFrieght.setEnabled(true);
                        txtHammali.setEnabled(true);
                        sno_flag = 1;
                        txtTo.requestFocusInWindow();
                    }
                    else
                    {
                        JOptionPane.showMessageDialog(null, sno + " SNO is already taken. Please select another");
                        if(sno_flag != 1)
                            txtSno.setText("");
                        txtSno.requestFocusInWindow();

                    }
            }
            else
            {
                lblValidate.setText("Enter the SNO!!!");
                txtSno.requestFocusInWindow();
            }
       
       }
       
       catch(Exception e)
       {
           JOptionPane.showMessageDialog(null, e);
       }
      
    }//GEN-LAST:event_jLabel18MouseClicked

    private void txtSnoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSnoKeyTyped
        // TODO add your handling code here:
        char vchar = evt.getKeyChar();
      
       if(!(Character.isDigit(vchar)) || (vchar == KeyEvent.VK_BACK_SPACE) || (vchar == KeyEvent.VK_DELETE))
       {
           evt.consume();
       }
    }//GEN-LAST:event_txtSnoKeyTyped

    private void txtFrieghtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFrieghtKeyTyped
        // TODO add your handling code here:
       char vchar = evt.getKeyChar();
      
       if(!(Character.isDigit(vchar)) || (vchar == KeyEvent.VK_BACK_SPACE) || (vchar == KeyEvent.VK_DELETE))
       {
           evt.consume();
       }
    }//GEN-LAST:event_txtFrieghtKeyTyped

    private void txtHammaliKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtHammaliKeyTyped
        // TODO add your handling code here:
       char vchar = evt.getKeyChar();
      
       if(!(Character.isDigit(vchar)) || (vchar == KeyEvent.VK_BACK_SPACE) || (vchar == KeyEvent.VK_DELETE))
       {
           evt.consume();
       }
    }//GEN-LAST:event_txtHammaliKeyTyped

    private void txtBiltyKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBiltyKeyTyped
        // TODO add your handling code here:
        char vchar = evt.getKeyChar();
      
       if(!(Character.isDigit(vchar)) || (vchar == KeyEvent.VK_BACK_SPACE) || (vchar == KeyEvent.VK_DELETE))
       {
           evt.consume();
       }
    }//GEN-LAST:event_txtBiltyKeyTyped

    private void txtGrandKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtGrandKeyTyped
        // TODO add your handling code here:
       char vchar = evt.getKeyChar();
      
       if(!(Character.isDigit(vchar)) || (vchar == KeyEvent.VK_BACK_SPACE) || (vchar == KeyEvent.VK_DELETE))
       {
           evt.consume();
       }
    }//GEN-LAST:event_txtGrandKeyTyped

    private void txtPackagesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPackagesKeyTyped
        // TODO add your handling code here:
        char vchar = evt.getKeyChar();
      
       if(!(Character.isDigit(vchar)) || (vchar == KeyEvent.VK_BACK_SPACE) || (vchar == KeyEvent.VK_DELETE))
       {
           evt.consume();
       }
    }//GEN-LAST:event_txtPackagesKeyTyped

    private void txtWeightKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtWeightKeyTyped
        // TODO add your handling code here:
        char vchar = evt.getKeyChar();
      
       if(!(Character.isDigit(vchar)) || (vchar == KeyEvent.VK_BACK_SPACE) || (vchar == KeyEvent.VK_DELETE))
       {
           evt.consume();
       }
    }//GEN-LAST:event_txtWeightKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BuiltyFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BuiltyFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BuiltyFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BuiltyFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BuiltyFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalculate;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnCreate;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnExit;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblValidate;
    private javax.swing.JRadioButton rdbBilled;
    private javax.swing.JRadioButton rdbPaid;
    private javax.swing.JRadioButton rdbToPay;
    private javax.swing.JTable tblData;
    private javax.swing.JTextField txtBilty;
    private javax.swing.JTextField txtConsignee;
    private javax.swing.JTextField txtConsignee_GST;
    private javax.swing.JTextField txtConsignor;
    private javax.swing.JTextField txtConsignor_GST;
    private javax.swing.JTextField txtDate;
    private javax.swing.JTextField txtDescription;
    private javax.swing.JTextField txtFrieght;
    private javax.swing.JTextField txtFrom;
    private javax.swing.JTextField txtGrand;
    private javax.swing.JTextField txtHammali;
    private javax.swing.JTextField txtPackages;
    private javax.swing.JTextField txtSno;
    private javax.swing.JTextField txtTo;
    private javax.swing.JTextField txtWeight;
    // End of variables declaration//GEN-END:variables
}
